"""CTDA condition function table extracted from FO76 definitions.

This module provides the complete mapping of CTDA condition function indices
to their human-readable names and parameter types, along with helper functions
for decoding and formatting condition data from Fallout 76 ESM files.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Parameter type constants
# ---------------------------------------------------------------------------
PT_NONE = 0
PT_STRING = 1
PT_INTEGER = 2
PT_FLOAT = 3
PT_FORMID = 4
PT_ACTOR_VALUE = 5
PT_AXIS = 6

# ---------------------------------------------------------------------------
# CTDA condition function table  (538 entries)
# Key   = function index (uint16 in the CTDA record)
# Value = (function_name, param1_type, param2_type)
# ---------------------------------------------------------------------------
CTDA_FUNCTIONS: dict[int, tuple[str, int, int]] = {
    0: ("GetWantBlocking", PT_NONE, PT_NONE),
    1: ("GetDistance", PT_FORMID, PT_NONE),
    5: ("GetLocked", PT_NONE, PT_NONE),
    6: ("GetPos", PT_AXIS, PT_NONE),
    8: ("GetAngle", PT_AXIS, PT_NONE),
    10: ("GetStartingPos", PT_AXIS, PT_NONE),
    11: ("GetStartingAngle", PT_AXIS, PT_NONE),
    12: ("GetSecondsPassed", PT_NONE, PT_NONE),
    14: ("GetValue", PT_ACTOR_VALUE, PT_NONE),
    18: ("GetCurrentTime", PT_NONE, PT_NONE),
    24: ("GetScale", PT_NONE, PT_NONE),
    25: ("IsMoving", PT_NONE, PT_NONE),
    26: ("IsTurning", PT_NONE, PT_NONE),
    27: ("GetLineOfSight", PT_FORMID, PT_NONE),
    32: ("GetInSameCell", PT_FORMID, PT_NONE),
    35: ("GetDisabled", PT_NONE, PT_NONE),
    36: ("MenuMode", PT_INTEGER, PT_NONE),
    39: ("GetDisease", PT_NONE, PT_NONE),
    41: ("GetClothingValue", PT_NONE, PT_NONE),
    42: ("SameFaction", PT_FORMID, PT_NONE),
    43: ("SameRace", PT_FORMID, PT_NONE),
    44: ("SameSex", PT_FORMID, PT_NONE),
    45: ("GetDetected", PT_FORMID, PT_NONE),
    46: ("GetDead", PT_NONE, PT_NONE),
    47: ("GetItemCount", PT_FORMID, PT_NONE),
    48: ("GetGold", PT_NONE, PT_NONE),
    49: ("GetSleeping", PT_NONE, PT_NONE),
    50: ("GetTalkedToPC", PT_NONE, PT_NONE),
    56: ("GetQuestRunning", PT_FORMID, PT_NONE),
    58: ("GetStage", PT_FORMID, PT_NONE),
    59: ("GetStageDone", PT_FORMID, PT_INTEGER),
    60: ("GetFactionRankDifference", PT_FORMID, PT_NONE),
    61: ("GetAlarmed", PT_NONE, PT_NONE),
    62: ("IsRaining", PT_FORMID, PT_NONE),
    63: ("GetAttacked", PT_NONE, PT_NONE),
    64: ("GetIsCreature", PT_NONE, PT_NONE),
    65: ("GetLockLevel", PT_NONE, PT_NONE),
    66: ("GetShouldAttack", PT_FORMID, PT_NONE),
    67: ("GetInCell", PT_FORMID, PT_NONE),
    68: ("GetIsClass", PT_FORMID, PT_NONE),
    69: ("GetIsRace", PT_FORMID, PT_NONE),
    70: ("GetIsSex", PT_FORMID, PT_NONE),
    71: ("GetInFaction", PT_FORMID, PT_NONE),
    72: ("GetIsID", PT_FORMID, PT_NONE),
    73: ("GetFactionRank", PT_FORMID, PT_NONE),
    74: ("GetGlobalValue", PT_FORMID, PT_NONE),
    75: ("IsSnowing", PT_FORMID, PT_NONE),
    77: ("GetRandomPercent", PT_NONE, PT_NONE),
    79: ("WouldBeStealing", PT_FORMID, PT_NONE),
    80: ("GetLevel", PT_NONE, PT_NONE),
    81: ("IsRotating", PT_NONE, PT_NONE),
    84: ("GetDeadCount", PT_FORMID, PT_NONE),
    91: ("GetIsAlerted", PT_NONE, PT_NONE),
    98: ("GetPlayerControlsDisabled", PT_INTEGER, PT_NONE),
    99: ("GetHeadingAngle", PT_FORMID, PT_NONE),
    101: ("IsWeaponMagicOut", PT_NONE, PT_NONE),
    102: ("IsTorchOut", PT_NONE, PT_NONE),
    103: ("IsShieldOut", PT_NONE, PT_NONE),
    106: ("IsFacingUp", PT_NONE, PT_NONE),
    107: ("GetKnockedState", PT_NONE, PT_NONE),
    108: ("GetWeaponAnimType", PT_NONE, PT_NONE),
    109: ("IsWeaponSkillType", PT_ACTOR_VALUE, PT_NONE),
    110: ("GetCurrentAIPackage", PT_NONE, PT_NONE),
    111: ("IsWaiting", PT_NONE, PT_NONE),
    112: ("IsIdlePlaying", PT_NONE, PT_NONE),
    116: ("IsIntimidatedbyPlayer", PT_NONE, PT_NONE),
    117: ("IsPlayerInRegion", PT_FORMID, PT_NONE),
    118: ("GetActorAggroRadiusViolated", PT_NONE, PT_NONE),
    122: ("GetCrime", PT_FORMID, PT_INTEGER),
    123: ("IsGreetingPlayer", PT_NONE, PT_NONE),
    125: ("IsGuard", PT_NONE, PT_NONE),
    127: ("HasBeenEaten", PT_NONE, PT_NONE),
    128: ("GetStaminaPercentage", PT_NONE, PT_NONE),
    129: ("HasBeenRead", PT_NONE, PT_NONE),
    130: ("GetDying", PT_NONE, PT_NONE),
    131: ("GetSceneActionPercent", PT_FORMID, PT_INTEGER),
    132: ("WouldRefuseCommand", PT_FORMID, PT_NONE),
    133: ("SameFactionAsPC", PT_NONE, PT_NONE),
    134: ("SameRaceAsPC", PT_NONE, PT_NONE),
    135: ("SameSexAsPC", PT_NONE, PT_NONE),
    136: ("GetIsReference", PT_FORMID, PT_NONE),
    141: ("IsTalking", PT_NONE, PT_NONE),
    142: ("GetComponentCount", PT_FORMID, PT_NONE),
    143: ("GetCurrentAIProcedure", PT_NONE, PT_NONE),
    144: ("GetTrespassWarningLevel", PT_NONE, PT_NONE),
    145: ("IsTrespassing", PT_NONE, PT_NONE),
    146: ("IsInMyOwnedCell", PT_NONE, PT_NONE),
    147: ("GetWindSpeed", PT_NONE, PT_NONE),
    148: ("GetCurrentWeatherPercent", PT_FORMID, PT_NONE),
    149: ("GetIsCurrentWeather", PT_FORMID, PT_FORMID),
    150: ("IsContinuingPackagePCNear", PT_NONE, PT_NONE),
    152: ("GetIsCrimeFaction", PT_FORMID, PT_NONE),
    153: ("CanHaveFlames", PT_NONE, PT_NONE),
    154: ("HasFlames", PT_NONE, PT_NONE),
    157: ("GetOpenState", PT_NONE, PT_NONE),
    159: ("GetSitting", PT_NONE, PT_NONE),
    161: ("GetIsCurrentPackage", PT_FORMID, PT_NONE),
    162: ("IsCurrentFurnitureRef", PT_FORMID, PT_NONE),
    163: ("IsCurrentFurnitureObj", PT_FORMID, PT_NONE),
    170: ("GetDayOfWeek", PT_NONE, PT_NONE),
    172: ("GetTalkedToPCParam", PT_FORMID, PT_NONE),
    175: ("IsPCSleeping", PT_NONE, PT_NONE),
    176: ("IsPCAMurderer", PT_NONE, PT_NONE),
    180: ("HasSameEditorLocationAsRef", PT_FORMID, PT_FORMID),
    181: ("HasSameEditorLocationAsRefAlias", PT_FORMID, PT_FORMID),
    182: ("GetEquipped", PT_FORMID, PT_NONE),
    185: ("IsSwimming", PT_NONE, PT_NONE),
    190: ("GetAmountSoldStolen", PT_NONE, PT_NONE),
    192: ("GetIgnoreCrime", PT_NONE, PT_NONE),
    193: ("GetPCExpelled", PT_FORMID, PT_NONE),
    195: ("GetPCFactionMurder", PT_FORMID, PT_NONE),
    197: ("GetPCEnemyofFaction", PT_FORMID, PT_NONE),
    199: ("GetPCFactionAttack", PT_FORMID, PT_NONE),
    203: ("GetDestroyed", PT_NONE, PT_NONE),
    214: ("HasMagicEffect", PT_FORMID, PT_NONE),
    215: ("GetDefaultOpen", PT_NONE, PT_NONE),
    223: ("IsSpellTarget", PT_FORMID, PT_NONE),
    224: ("GetVATSMode", PT_NONE, PT_NONE),
    225: ("GetPersuasionNumber", PT_NONE, PT_NONE),
    226: ("GetVampireFeed", PT_NONE, PT_NONE),
    227: ("GetCannibal", PT_NONE, PT_NONE),
    228: ("GetIsClassDefault", PT_FORMID, PT_NONE),
    229: ("GetClassDefaultMatch", PT_NONE, PT_NONE),
    230: ("GetInCellParam", PT_FORMID, PT_FORMID),
    231: ("GetPlayerDialogueInput", PT_NONE, PT_NONE),
    235: ("GetVatsTargetHeight", PT_NONE, PT_NONE),
    237: ("GetIsGhost", PT_NONE, PT_NONE),
    242: ("GetUnconscious", PT_NONE, PT_NONE),
    244: ("GetRestrained", PT_NONE, PT_NONE),
    246: ("GetIsUsedItem", PT_FORMID, PT_NONE),
    247: ("GetIsUsedItemType", PT_INTEGER, PT_NONE),
    248: ("IsScenePlaying", PT_FORMID, PT_NONE),
    249: ("IsInDialogueWithPlayer", PT_NONE, PT_NONE),
    250: ("GetLocationCleared", PT_FORMID, PT_NONE),
    254: ("GetIsPlayableRace", PT_NONE, PT_NONE),
    255: ("GetOffersServicesNow", PT_NONE, PT_NONE),
    258: ("HasAssociationType", PT_FORMID, PT_NONE),
    259: ("HasFamilyRelationship", PT_FORMID, PT_NONE),
    261: ("HasParentRelationship", PT_FORMID, PT_NONE),
    262: ("IsWarningAbout", PT_FORMID, PT_NONE),
    263: ("IsWeaponOut", PT_NONE, PT_NONE),
    264: ("HasSpell", PT_FORMID, PT_NONE),
    265: ("IsTimePassing", PT_NONE, PT_NONE),
    266: ("IsPleasant", PT_FORMID, PT_NONE),
    267: ("IsCloudy", PT_FORMID, PT_NONE),
    274: ("IsSmallBump", PT_NONE, PT_NONE),
    277: ("GetBaseValue", PT_ACTOR_VALUE, PT_NONE),
    278: ("IsOwner", PT_FORMID, PT_NONE),
    280: ("IsCellOwner", PT_FORMID, PT_FORMID),
    282: ("IsHorseStolen", PT_NONE, PT_NONE),
    285: ("IsLeftUp", PT_NONE, PT_NONE),
    286: ("IsSneaking", PT_NONE, PT_NONE),
    287: ("IsRunning", PT_NONE, PT_NONE),
    288: ("GetFriendHit", PT_NONE, PT_NONE),
    289: ("IsInCombat", PT_INTEGER, PT_NONE),
    300: ("IsInInterior", PT_NONE, PT_NONE),
    304: ("IsWaterObject", PT_NONE, PT_NONE),
    305: ("GetPlayerAction", PT_NONE, PT_NONE),
    306: ("IsActorUsingATorch", PT_NONE, PT_NONE),
    309: ("IsXBox", PT_NONE, PT_NONE),
    310: ("GetInWorldspace", PT_FORMID, PT_NONE),
    312: ("GetPCMiscStat", PT_INTEGER, PT_NONE),
    313: ("GetPairedAnimation", PT_NONE, PT_NONE),
    314: ("IsActorAVictim", PT_NONE, PT_NONE),
    315: ("GetTotalPersuasionNumber", PT_NONE, PT_NONE),
    318: ("GetIdleDoneOnce", PT_NONE, PT_NONE),
    320: ("GetNoRumors", PT_NONE, PT_NONE),
    323: ("GetCombatState", PT_NONE, PT_NONE),
    325: ("GetWithinPackageLocation", PT_FORMID, PT_NONE),
    327: ("IsRidingMount", PT_NONE, PT_NONE),
    329: ("IsFleeing", PT_NONE, PT_NONE),
    332: ("IsInDangerousWater", PT_NONE, PT_NONE),
    338: ("GetIgnoreFriendlyHits", PT_NONE, PT_NONE),
    339: ("IsPlayersLastRiddenMount", PT_NONE, PT_NONE),
    353: ("IsActor", PT_NONE, PT_NONE),
    354: ("IsEssential", PT_NONE, PT_NONE),
    358: ("IsPlayerMovingIntoNewSpace", PT_NONE, PT_NONE),
    359: ("GetInCurrentLocation", PT_FORMID, PT_NONE),
    360: ("GetInCurrentLocationAlias", PT_FORMID, PT_NONE),
    361: ("GetTimeDead", PT_NONE, PT_NONE),
    362: ("HasLinkedRef", PT_FORMID, PT_NONE),
    365: ("IsChild", PT_NONE, PT_NONE),
    366: ("GetStolenItemValueNoCrime", PT_FORMID, PT_NONE),
    367: ("GetLastPlayerAction", PT_NONE, PT_NONE),
    368: ("IsPlayerActionActive", PT_INTEGER, PT_NONE),
    370: ("IsTalkingActivatorActor", PT_FORMID, PT_NONE),
    371: ("IsOnChems", PT_NONE, PT_NONE),
    372: ("IsInList", PT_FORMID, PT_NONE),
    373: ("GetStolenItemValue", PT_FORMID, PT_NONE),
    375: ("GetCrimeGoldViolent", PT_FORMID, PT_NONE),
    376: ("GetCrimeGoldNonviolent", PT_FORMID, PT_NONE),
    378: ("IsOwnedBy", PT_FORMID, PT_NONE),
    380: ("GetCommandDistance", PT_NONE, PT_NONE),
    381: ("GetCommandLocationDistance", PT_NONE, PT_NONE),
    390: ("GetHitLocation", PT_NONE, PT_NONE),
    391: ("IsPC1stPerson", PT_NONE, PT_NONE),
    396: ("GetCauseofDeath", PT_NONE, PT_NONE),
    397: ("IsLimbGone", PT_INTEGER, PT_NONE),
    398: ("IsWeaponInList", PT_FORMID, PT_NONE),
    402: ("IsBribedbyPlayer", PT_NONE, PT_NONE),
    403: ("GetRelationshipRank", PT_FORMID, PT_NONE),
    407: ("GetVATSValue", PT_INTEGER, PT_INTEGER),
    408: ("IsKiller", PT_FORMID, PT_NONE),
    409: ("IsKillerObject", PT_FORMID, PT_NONE),
    410: ("GetFactionCombatReaction", PT_FORMID, PT_NONE),
    414: ("Exists", PT_FORMID, PT_NONE),
    415: ("GetGroupMemberCount", PT_NONE, PT_NONE),
    416: ("GetGroupTargetCount", PT_NONE, PT_NONE),
    426: ("GetIsVoiceType", PT_FORMID, PT_NONE),
    427: ("GetPlantedExplosive", PT_NONE, PT_NONE),
    429: ("IsScenePackageRunning", PT_NONE, PT_NONE),
    430: ("GetHealthPercentage", PT_NONE, PT_NONE),
    432: ("GetIsObjectType", PT_INTEGER, PT_NONE),
    434: ("PlayerVisualDetection", PT_NONE, PT_NONE),
    435: ("PlayerAudioDetection", PT_NONE, PT_NONE),
    437: ("GetIsCreatureType", PT_INTEGER, PT_NONE),
    438: ("HasKey", PT_FORMID, PT_NONE),
    439: ("IsFurnitureEntryType", PT_INTEGER, PT_NONE),
    444: ("GetInCurrentLocationFormList", PT_FORMID, PT_NONE),
    445: ("GetInZone", PT_FORMID, PT_NONE),
    446: ("GetVelocity", PT_AXIS, PT_NONE),
    447: ("GetGraphVariableFloat", PT_STRING, PT_NONE),
    448: ("HasPerk", PT_FORMID, PT_NONE),
    449: ("GetFactionRelation", PT_FORMID, PT_NONE),
    450: ("IsLastIdlePlayed", PT_FORMID, PT_NONE),
    453: ("GetPlayerTeammate", PT_NONE, PT_NONE),
    454: ("GetPlayerTeammateCount", PT_NONE, PT_NONE),
    458: ("GetActorCrimePlayerEnemy", PT_NONE, PT_NONE),
    459: ("GetCrimeGold", PT_FORMID, PT_NONE),
    463: ("IsPlayerGrabbedRef", PT_FORMID, PT_NONE),
    465: ("GetKeywordItemCount", PT_FORMID, PT_NONE),
    470: ("GetDestructionStage", PT_NONE, PT_NONE),
    473: ("GetIsAlignment", PT_INTEGER, PT_NONE),
    476: ("IsProtected", PT_NONE, PT_NONE),
    477: ("GetThreatRatio", PT_FORMID, PT_NONE),
    479: ("GetIsUsedItemEquipType", PT_FORMID, PT_NONE),
    483: ("GetPlayerActivated", PT_NONE, PT_NONE),
    485: ("GetFullyEnabledActorsInHigh", PT_NONE, PT_NONE),
    487: ("IsCarryable", PT_NONE, PT_NONE),
    488: ("GetConcussed", PT_NONE, PT_NONE),
    491: ("GetMapMarkerVisible", PT_NONE, PT_NONE),
    493: ("PlayerKnows", PT_FORMID, PT_NONE),
    494: ("GetPermanentValue", PT_ACTOR_VALUE, PT_NONE),
    495: ("GetKillingBlowLimb", PT_NONE, PT_NONE),
    497: ("CanPayCrimeGold", PT_FORMID, PT_NONE),
    499: ("GetDaysInJail", PT_NONE, PT_NONE),
    500: ("EPAlchemyGetMakingPoison", PT_NONE, PT_NONE),
    501: ("EPAlchemyEffectHasKeyword", PT_FORMID, PT_NONE),
    503: ("GetAllowWorldInteractions", PT_NONE, PT_NONE),
    506: ("DialogueGetAv", PT_ACTOR_VALUE, PT_NONE),
    507: ("DialogueHasPerk", PT_FORMID, PT_NONE),
    508: ("GetLastHitCritical", PT_NONE, PT_NONE),
    510: ("DialogueGetItemCount", PT_FORMID, PT_NONE),
    511: ("LastCrippledCondition", PT_ACTOR_VALUE, PT_NONE),
    512: ("HasSharedPowerGrid", PT_FORMID, PT_NONE),
    513: ("IsCombatTarget", PT_FORMID, PT_NONE),
    515: ("GetVATSRightAreaFree", PT_FORMID, PT_NONE),
    516: ("GetVATSLeftAreaFree", PT_FORMID, PT_NONE),
    517: ("GetVATSBackAreaFree", PT_FORMID, PT_NONE),
    518: ("GetVATSFrontAreaFree", PT_FORMID, PT_NONE),
    519: ("GetIsLockBroken", PT_NONE, PT_NONE),
    520: ("IsPS3", PT_NONE, PT_NONE),
    521: ("IsWindowsPC", PT_NONE, PT_NONE),
    522: ("GetVATSRightTargetVisible", PT_FORMID, PT_NONE),
    523: ("GetVATSLeftTargetVisible", PT_FORMID, PT_NONE),
    524: ("GetVATSBackTargetVisible", PT_FORMID, PT_NONE),
    525: ("GetVATSFrontTargetVisible", PT_FORMID, PT_NONE),
    528: ("IsInCriticalStage", PT_INTEGER, PT_NONE),
    530: ("GetXPForNextLevel", PT_NONE, PT_NONE),
    533: ("GetInfamy", PT_FORMID, PT_NONE),
    534: ("GetInfamyViolent", PT_FORMID, PT_NONE),
    535: ("GetInfamyNonViolent", PT_FORMID, PT_NONE),
    536: ("GetTypeCommandPerforming", PT_NONE, PT_NONE),
    543: ("GetQuestCompleted", PT_FORMID, PT_NONE),
    544: ("GetSpeechChallengeSuccessLevel", PT_NONE, PT_NONE),
    547: ("IsGoreDisabled", PT_NONE, PT_NONE),
    550: ("IsSceneActionComplete", PT_FORMID, PT_INTEGER),
    552: ("GetSpellUsageNum", PT_FORMID, PT_NONE),
    554: ("GetActorsInHigh", PT_NONE, PT_NONE),
    555: ("HasLoaded3D", PT_NONE, PT_NONE),
    560: ("HasKeyword", PT_FORMID, PT_NONE),
    561: ("HasRefType", PT_FORMID, PT_NONE),
    562: ("LocationHasKeyword", PT_FORMID, PT_NONE),
    563: ("LocationHasRefType", PT_FORMID, PT_NONE),
    565: ("GetIsEditorLocation", PT_FORMID, PT_NONE),
    566: ("GetIsAliasRef", PT_FORMID, PT_NONE),
    567: ("GetIsEditorLocationAlias", PT_FORMID, PT_NONE),
    568: ("IsSprinting", PT_NONE, PT_NONE),
    569: ("IsBlocking", PT_NONE, PT_NONE),
    570: ("HasEquippedSpell", PT_INTEGER, PT_NONE),
    571: ("GetCurrentCastingType", PT_INTEGER, PT_NONE),
    572: ("GetCurrentDeliveryType", PT_INTEGER, PT_NONE),
    574: ("GetAttackState", PT_NONE, PT_NONE),
    576: ("GetEventData", PT_INTEGER, PT_INTEGER),
    577: ("IsCloserToAThanB", PT_FORMID, PT_FORMID),
    578: ("LevelMinusPCLevel", PT_NONE, PT_NONE),
    579: ("EditorLocationHasKeyword", PT_FORMID, PT_NONE),
    580: ("IsBleedingOut", PT_NONE, PT_NONE),
    584: ("GetRelativeAngle", PT_FORMID, PT_AXIS),
    589: ("GetMovementDirection", PT_NONE, PT_NONE),
    590: ("IsInScene", PT_NONE, PT_NONE),
    591: ("GetRefTypeDeadCount", PT_FORMID, PT_NONE),
    592: ("GetRefTypeAliveCount", PT_FORMID, PT_NONE),
    594: ("GetIsFlying", PT_NONE, PT_NONE),
    595: ("IsCurrentSpell", PT_FORMID, PT_INTEGER),
    596: ("SpellHasKeyword", PT_INTEGER, PT_FORMID),
    597: ("GetEquippedItemType", PT_INTEGER, PT_NONE),
    598: ("GetLocationAliasCleared", PT_FORMID, PT_NONE),
    600: ("GetLocationAliasRefTypeDeadCount", PT_FORMID, PT_FORMID),
    601: ("GetLocationAliasRefTypeAliveCount", PT_FORMID, PT_FORMID),
    602: ("IsWardState", PT_INTEGER, PT_NONE),
    603: ("IsInSameCurrentLocationAsRef", PT_FORMID, PT_FORMID),
    604: ("IsInSameCurrentLocationAsRefAlias", PT_FORMID, PT_FORMID),
    605: ("LocationAliasIsLocation", PT_FORMID, PT_FORMID),
    606: ("GetKeywordDataForLocation", PT_FORMID, PT_NONE),
    608: ("GetKeywordDataForAlias", PT_FORMID, PT_FORMID),
    610: ("LocationAliasHasKeyword", PT_FORMID, PT_FORMID),
    611: ("IsNullPackageData", PT_FORMID, PT_NONE),
    612: ("GetNumericPackageData", PT_FORMID, PT_NONE),
    613: ("IsPlayerRadioOn", PT_NONE, PT_NONE),
    614: ("GetPlayerRadioFrequency", PT_NONE, PT_NONE),
    615: ("GetHighestRelationshipRank", PT_NONE, PT_NONE),
    616: ("GetLowestRelationshipRank", PT_NONE, PT_NONE),
    617: ("HasAssociationTypeAny", PT_FORMID, PT_NONE),
    618: ("HasFamilyRelationshipAny", PT_NONE, PT_NONE),
    619: ("GetPathingTargetOffset", PT_AXIS, PT_NONE),
    620: ("GetPathingTargetAngleOffset", PT_AXIS, PT_NONE),
    621: ("GetPathingTargetSpeed", PT_NONE, PT_NONE),
    622: ("GetPathingTargetSpeedAngle", PT_AXIS, PT_NONE),
    623: ("GetMovementSpeed", PT_NONE, PT_NONE),
    624: ("GetInContainer", PT_FORMID, PT_NONE),
    625: ("IsLocationLoaded", PT_FORMID, PT_NONE),
    626: ("IsLocationAliasLoaded", PT_FORMID, PT_NONE),
    627: ("IsDualCasting", PT_NONE, PT_NONE),
    629: ("GetVMQuestVariable", PT_FORMID, PT_STRING),
    630: ("GetCombatAudioDetection", PT_NONE, PT_NONE),
    631: ("GetCombatVisualDetection", PT_NONE, PT_NONE),
    632: ("IsCasting", PT_NONE, PT_NONE),
    633: ("GetFlyingState", PT_NONE, PT_NONE),
    635: ("IsInFavorState", PT_NONE, PT_NONE),
    636: ("HasTwoHandedWeaponEquipped", PT_NONE, PT_NONE),
    637: ("IsFurnitureExitType", PT_INTEGER, PT_NONE),
    638: ("IsInFriendStatewithPlayer", PT_NONE, PT_NONE),
    639: ("GetWithinDistance", PT_FORMID, PT_FLOAT),
    640: ("GetValuePercent", PT_ACTOR_VALUE, PT_NONE),
    641: ("IsUnique", PT_NONE, PT_NONE),
    642: ("GetLastBumpDirection", PT_NONE, PT_NONE),
    644: ("GetInfoChallangeSuccess", PT_NONE, PT_NONE),
    645: ("GetIsInjured", PT_NONE, PT_NONE),
    646: ("GetIsCrashLandRequest", PT_NONE, PT_NONE),
    647: ("GetIsHastyLandRequest", PT_NONE, PT_NONE),
    650: ("IsLinkedTo", PT_FORMID, PT_FORMID),
    651: ("GetKeywordDataForCurrentLocation", PT_FORMID, PT_NONE),
    652: ("GetInSharedCrimeFaction", PT_FORMID, PT_NONE),
    654: ("GetBribeSuccess", PT_NONE, PT_NONE),
    655: ("GetIntimidateSuccess", PT_NONE, PT_NONE),
    656: ("GetArrestedState", PT_NONE, PT_NONE),
    657: ("GetArrestingActor", PT_NONE, PT_NONE),
    659: ("HasVMScript", PT_STRING, PT_NONE),
    660: ("GetVMScriptVariable", PT_STRING, PT_STRING),
    661: ("GetWorkshopResourceDamage", PT_ACTOR_VALUE, PT_NONE),
    664: ("HasValidRumorTopic", PT_FORMID, PT_NONE),
    672: ("IsAttacking", PT_NONE, PT_NONE),
    673: ("IsPowerAttacking", PT_NONE, PT_NONE),
    674: ("IsLastHostileActor", PT_NONE, PT_NONE),
    675: ("GetGraphVariableInt", PT_STRING, PT_NONE),
    678: ("ShouldAttackKill", PT_FORMID, PT_NONE),
    680: ("GetActivationHeight", PT_NONE, PT_NONE),
    682: ("WornHasKeyword", PT_FORMID, PT_NONE),
    683: ("GetPathingCurrentSpeed", PT_NONE, PT_NONE),
    684: ("GetPathingCurrentSpeedAngle", PT_AXIS, PT_NONE),
    691: ("GetWorkshopObjectCount", PT_FORMID, PT_NONE),
    693: ("EPMagic_SpellHasKeyword", PT_FORMID, PT_NONE),
    694: ("GetNoBleedoutRecovery", PT_NONE, PT_NONE),
    696: ("EPMagic_SpellHasSkill", PT_ACTOR_VALUE, PT_NONE),
    697: ("IsAttackType", PT_FORMID, PT_NONE),
    698: ("IsAllowedToFly", PT_NONE, PT_NONE),
    699: ("HasMagicEffectKeyword", PT_FORMID, PT_NONE),
    700: ("IsCommandedActor", PT_NONE, PT_NONE),
    701: ("IsStaggered", PT_NONE, PT_NONE),
    702: ("IsRecoiling", PT_NONE, PT_NONE),
    703: ("HasScopeWeaponEquipped", PT_NONE, PT_NONE),
    704: ("IsPathing", PT_NONE, PT_NONE),
    705: ("GetShouldHelp", PT_FORMID, PT_NONE),
    706: ("HasBoundWeaponEquipped", PT_INTEGER, PT_NONE),
    707: ("GetCombatTargetHasKeyword", PT_FORMID, PT_NONE),
    709: ("GetCombatGroupMemberCount", PT_NONE, PT_NONE),
    710: ("IsIgnoringCombat", PT_NONE, PT_NONE),
    711: ("GetLightLevel", PT_NONE, PT_NONE),
    713: ("SpellHasCastingPerk", PT_FORMID, PT_NONE),
    714: ("IsBeingRidden", PT_NONE, PT_NONE),
    715: ("IsUndead", PT_NONE, PT_NONE),
    716: ("GetRealHoursPassed", PT_NONE, PT_NONE),
    718: ("IsUnlockedDoor", PT_NONE, PT_NONE),
    719: ("IsHostileToActor", PT_FORMID, PT_NONE),
    720: ("GetTargetHeight", PT_FORMID, PT_NONE),
    721: ("IsPoison", PT_NONE, PT_NONE),
    722: ("WornApparelHasKeywordCount", PT_FORMID, PT_NONE),
    723: ("GetItemHealthPercent", PT_NONE, PT_NONE),
    724: ("EffectWasDualCast", PT_NONE, PT_NONE),
    725: ("GetKnockStateEnum", PT_NONE, PT_NONE),
    726: ("DoesNotExist", PT_NONE, PT_NONE),
    728: ("GetPlayerWalkAwayFromDialogueScene", PT_NONE, PT_NONE),
    729: ("GetActorStance", PT_NONE, PT_NONE),
    734: ("CanProduceForWorkshop", PT_NONE, PT_NONE),
    735: ("CanFlyHere", PT_NONE, PT_NONE),
    736: ("EPIsDamageType", PT_FORMID, PT_NONE),
    737: ("GetCurrentWeatherHasKeyword", PT_FORMID, PT_NONE),
    738: ("GetActorGunState", PT_NONE, PT_NONE),
    739: ("GetVoiceLineLength", PT_NONE, PT_NONE),
    741: ("ObjectTemplateItem_HasKeyword", PT_FORMID, PT_NONE),
    742: ("ObjectTemplateItem_HasUniqueKeyword", PT_FORMID, PT_NONE),
    743: ("ObjectTemplateItem_GetLevel", PT_NONE, PT_NONE),
    744: ("MovementIdleMatches", PT_INTEGER, PT_FORMID),
    745: ("GetActionData", PT_NONE, PT_NONE),
    746: ("GetActionDataShort", PT_INTEGER, PT_NONE),
    747: ("GetActionDataByte", PT_INTEGER, PT_NONE),
    748: ("GetActionDataFlag", PT_INTEGER, PT_NONE),
    749: ("ModdedItemHasKeyword", PT_FORMID, PT_NONE),
    750: ("GetAngryWithPlayer", PT_NONE, PT_NONE),
    751: ("IsCameraUnderWater", PT_NONE, PT_NONE),
    753: ("IsActorRefOwner", PT_FORMID, PT_NONE),
    754: ("HasActorRefOwner", PT_FORMID, PT_NONE),
    756: ("GetLoadedAmmoCount", PT_NONE, PT_NONE),
    757: ("IsTimeSpanSunrise", PT_NONE, PT_NONE),
    758: ("IsTimeSpanMorning", PT_NONE, PT_NONE),
    759: ("IsTimeSpanAfternoon", PT_NONE, PT_NONE),
    760: ("IsTimeSpanEvening", PT_NONE, PT_NONE),
    761: ("IsTimeSpanSunset", PT_NONE, PT_NONE),
    762: ("IsTimeSpanNight", PT_NONE, PT_NONE),
    763: ("IsTimeSpanMidnight", PT_NONE, PT_NONE),
    764: ("IsTimeSpanAnyDay", PT_NONE, PT_NONE),
    765: ("IsTimeSpanAnyNight", PT_NONE, PT_NONE),
    766: ("CurrentFurnitureHasKeyword", PT_FORMID, PT_NONE),
    767: ("GetWeaponEquipIndex", PT_NONE, PT_NONE),
    769: ("IsOverEncumbered", PT_NONE, PT_NONE),
    770: ("IsPackageRequestingBlockedIdles", PT_NONE, PT_NONE),
    771: ("GetActionDataInt", PT_NONE, PT_NONE),
    772: ("GetVATSRightMinusLeftAreaFree", PT_FORMID, PT_NONE),
    773: ("GetInIronSights", PT_FORMID, PT_NONE),
    774: ("GetActorStaggerDirection", PT_NONE, PT_NONE),
    775: ("GetActorStaggerMagnitude", PT_NONE, PT_NONE),
    776: ("WornCoversBipedSlot", PT_INTEGER, PT_NONE),
    777: ("GetInventoryValue", PT_NONE, PT_NONE),
    778: ("IsPlayerInConversation", PT_NONE, PT_NONE),
    779: ("IsInDialogueCamera", PT_NONE, PT_NONE),
    780: ("IsMyDialogueTargetPlayer", PT_NONE, PT_NONE),
    781: ("IsMyDialogueTargetActor", PT_NONE, PT_NONE),
    782: ("GetMyDialogueTargetDistance", PT_NONE, PT_NONE),
    783: ("IsSeatOccupied", PT_FORMID, PT_NONE),
    784: ("IsPlayerRiding", PT_NONE, PT_NONE),
    785: ("IsTryingEventCamera", PT_NONE, PT_NONE),
    786: ("UseLeftSideCamera", PT_NONE, PT_NONE),
    787: ("GetNoteType", PT_NONE, PT_NONE),
    788: ("LocationHasPlayerOwnedWorkshop", PT_NONE, PT_NONE),
    789: ("IsStartingAction", PT_NONE, PT_NONE),
    790: ("IsMidAction", PT_NONE, PT_NONE),
    791: ("IsWeaponChargeAttack", PT_NONE, PT_NONE),
    792: ("IsInWorkshopMode", PT_NONE, PT_NONE),
    793: ("IsWeaponChargingHoldAttack", PT_NONE, PT_NONE),
    794: ("IsEncounterAbovePlayerLevel", PT_NONE, PT_NONE),
    795: ("IsMeleeAttacking", PT_NONE, PT_NONE),
    796: ("GetVATSQueuedTargetsUnique", PT_NONE, PT_NONE),
    797: ("GetCurrentLocationCleared", PT_NONE, PT_NONE),
    798: ("IsPowered", PT_NONE, PT_NONE),
    799: ("GetTransmitterDistance", PT_NONE, PT_NONE),
    800: ("GetCameraPlaybackTime", PT_NONE, PT_NONE),
    801: ("IsInWater", PT_NONE, PT_NONE),
    802: ("GetWithinActivateDistance", PT_FORMID, PT_NONE),
    803: ("IsUnderWater", PT_NONE, PT_NONE),
    804: ("IsInSameSpace", PT_FORMID, PT_NONE),
    805: ("LocationAllowsReset", PT_NONE, PT_NONE),
    806: ("GetVATSBackRightAreaFree", PT_FORMID, PT_NONE),
    807: ("GetVATSBackLeftAreaFree", PT_FORMID, PT_NONE),
    808: ("GetVATSBackRightTargetVisible", PT_FORMID, PT_NONE),
    809: ("GetVATSBackLeftTargetVisible", PT_FORMID, PT_NONE),
    810: ("GetVATSTargetLimbVisible", PT_FORMID, PT_NONE),
    811: ("IsPlayerListening", PT_FLOAT, PT_NONE),
    812: ("GetPathingRequestedQuickTurn", PT_NONE, PT_NONE),
    813: ("EPIsCalculatingBaseDamage", PT_NONE, PT_NONE),
    814: ("GetReanimating", PT_NONE, PT_NONE),
    817: ("IsInRobotWorkbench", PT_NONE, PT_NONE),
    818: ("IsActorsTurfActive", PT_NONE, PT_NONE),
    828: ("GetIsPlayer", PT_NONE, PT_NONE),
    832: ("GetStageUniqueQuest", PT_FORMID, PT_NONE),
    833: ("GetStageDoneUniqueQuest", PT_FORMID, PT_INTEGER),
    834: ("GetVMQuestVariableUnique", PT_FORMID, PT_STRING),
    835: ("IsWorkshopOwner", PT_FORMID, PT_NONE),
    836: ("IsWorkshopClaimant", PT_FORMID, PT_NONE),
    837: ("IsActivePlayer", PT_NONE, PT_NONE),
    839: ("IsMemberOfAPlayerTeam", PT_NONE, PT_NONE),
    840: ("IsWaterConsumeSpell", PT_FORMID, PT_NONE),
    841: ("IsWaterContactSpell", PT_FORMID, PT_NONE),
    842: ("IsPlayerInFriendlyWorkshop", PT_NONE, PT_NONE),
    843: ("GetJunkItemCount", PT_NONE, PT_NONE),
    844: ("GetIsCurrentLocationExact", PT_FORMID, PT_NONE),
    845: ("GetIsEditorLocationExact", PT_FORMID, PT_NONE),
    846: ("GetActorValueForCurrentLocation", PT_ACTOR_VALUE, PT_FORMID),
    849: ("GetIsInRegion", PT_FORMID, PT_NONE),
    850: ("GetInAcousticSpace", PT_FORMID, PT_NONE),
    851: ("IsPowerArmorOwner", PT_NONE, PT_NONE),
    852: ("GetCurrency", PT_FORMID, PT_NONE),
    853: ("HasLearnedRecipe", PT_FORMID, PT_NONE),
    854: ("HasActiveMagicEffect", PT_FORMID, PT_NONE),
    855: ("HasBeenSearched", PT_NONE, PT_NONE),
    856: ("GetQuestRunningUnique", PT_FORMID, PT_NONE),
    857: ("GetNumTimesCompletedQuest", PT_FORMID, PT_NONE),
    858: ("WorkshopOwnerHasPerk", PT_FORMID, PT_NONE),
    859: ("HasEntitlement", PT_FORMID, PT_NONE),
    860: ("IsQuickplayer", PT_NONE, PT_NONE),
    861: ("IsVisitor", PT_NONE, PT_NONE),
    862: ("IsInWorkshop", PT_NONE, PT_NONE),
    863: ("IsInWorkshopOwned", PT_FORMID, PT_NONE),
    864: ("IsJunkItem", PT_NONE, PT_NONE),
    865: ("IsInWeather", PT_FORMID, PT_NONE),
    867: ("GetQuickplayModeLoadingInto", PT_NONE, PT_NONE),
    868: ("IsInitiatingFastTravel", PT_NONE, PT_NONE),
    869: ("GetQuickplayKeywordLoadingInto", PT_FORMID, PT_NONE),
    870: ("GetNumActiveEffectsWithKeyword", PT_FORMID, PT_NONE),
    871: ("GetNumActiveSpellsWithKeyword", PT_FORMID, PT_NONE),
    872: ("GatLastHitHealthDamageAmount", PT_NONE, PT_NONE),
    873: ("GatLastHitTotalDamageAmount", PT_NONE, PT_NONE),
    874: ("GatLastHitDamageSourceType", PT_NONE, PT_NONE),
    875: ("IsTrueForConditionForm", PT_FORMID, PT_NONE),
    876: ("IsActiveQuest", PT_FORMID, PT_NONE),
    877: ("IsFullHealth", PT_NONE, PT_NONE),
    878: ("CHAL_IsTargetWeaponMelee", PT_NONE, PT_NONE),
    879: ("CHAL_IsTargetWeaponRanged", PT_NONE, PT_NONE),
    880: ("CHAL_IsTargetWeaponThrown", PT_NONE, PT_NONE),
    881: ("CHAL_GetTargetWeaponDamageType", PT_FORMID, PT_NONE),
    882: ("CHAL_DoesTargetWeaponHaveKeyword", PT_FORMID, PT_NONE),
    884: ("CHAL_IsTargetWorkshopRecipeInCategory", PT_FORMID, PT_NONE),
    885: ("GetLastFallDamage", PT_NONE, PT_NONE),
    886: ("IsPlayerInCamp", PT_NONE, PT_NONE),
    887: ("GetLastHitLethal", PT_NONE, PT_NONE),
    888: ("IsPlayerTeammate", PT_NONE, PT_NONE),
    889: ("IsPlayerCombatOpponent", PT_NONE, PT_NONE),
    890: ("HasPerkCardEquipped", PT_FORMID, PT_INTEGER),
}

# ---------------------------------------------------------------------------
# Comparison operator mapping  (3-bit field from CTDA op_flags byte)
# ---------------------------------------------------------------------------
CTDA_OPERATORS: dict[int, str] = {
    0: "==", 1: "!=", 2: ">", 3: ">=", 4: "<", 5: "<=",
}

# ---------------------------------------------------------------------------
# Run-on target mapping
# ---------------------------------------------------------------------------
CTDA_RUN_ON: dict[int, str] = {
    0: "Subject", 1: "Target", 2: "Reference", 3: "CombatTarget",
    4: "LinkedReference", 5: "QuestAlias", 6: "PackageData",
    7: "EventData", 8: "CommandTarget",
}


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def function_name(index: int) -> str:
    """Get human-readable function name for a condition function index."""
    entry = CTDA_FUNCTIONS.get(index)
    return entry[0] if entry else f"Unknown_{index}"


def function_param_types(index: int) -> tuple[int, int]:
    """Get (param1_type, param2_type) for a function index."""
    entry = CTDA_FUNCTIONS.get(index)
    return (entry[1], entry[2]) if entry else (PT_NONE, PT_NONE)


def operator_str(op_byte: int) -> str:
    """Decode the comparison operator from the CTDA op_flags byte."""
    op_code = (op_byte >> 5) & 0x7
    return CTDA_OPERATORS.get(op_code, f"?op{op_code}")


def run_on_str(run_on: int) -> str:
    """Get human-readable run-on target name."""
    return CTDA_RUN_ON.get(run_on, f"Unknown({run_on})")


def format_param(value: int, param_type: int, cis_str: str | None) -> str:
    """Format a condition parameter value based on its type."""
    if param_type == PT_STRING and cis_str:
        return f'"{cis_str}"'
    if param_type == PT_FORMID:
        return f"0x{value:08X}"
    if param_type == PT_ACTOR_VALUE:
        return str(value)
    if param_type == PT_AXIS:
        return {0: "X", 1: "Y", 2: "Z"}.get(value, str(value))
    if param_type == PT_FLOAT:
        import struct
        f_val = struct.unpack("<f", struct.pack("<I", value))[0]
        return f"{f_val:.2f}"
    if param_type == PT_INTEGER:
        return str(value)
    return ""


def format_condition_summary(
    func_idx: int,
    op_byte: int,
    comp_value: float,
    param1: int,
    param2: int,
    cis1: str | None,
    cis2: str | None,
    run_on: int,
) -> str:
    """Format a complete condition into a human-readable summary string."""
    name = function_name(func_idx)
    op = operator_str(op_byte)
    pt1, pt2 = function_param_types(func_idx)

    params = []
    p1_str = format_param(param1, pt1, cis1)
    if p1_str:
        params.append(p1_str)
    p2_str = format_param(param2, pt2, cis2)
    if p2_str:
        params.append(p2_str)

    # Format comparison value
    if comp_value == int(comp_value):
        comp_str = f"{int(comp_value)}"
    else:
        comp_str = f"{comp_value:.2f}"

    run_on_name = run_on_str(run_on)

    call = f"{name}({', '.join(params)})" if params else f"{name}()"
    return f"{call} {op} {comp_str} [on {run_on_name}]"
