"""Record type registry and metadata."""
from __future__ import annotations

# Human-readable names for record types
TYPE_NAMES: dict[str, str] = {
    "AACT": "Action",
    "ACHR": "Placed NPC",
    "ACTI": "Activator",
    "ALCH": "Ingestible",
    "AMMO": "Ammunition",
    "ANIO": "Animated Object",
    "ARMA": "Armor Addon",
    "ARMO": "Armor",
    "ARTO": "Art Object",
    "ASPC": "Acoustic Space",
    "AVIF": "Actor Value",
    "BOOK": "Book/Note/Holotape",
    "CELL": "Cell",
    "CLAS": "Class",
    "CLMT": "Climate",
    "COBJ": "Constructible Object",
    "COLL": "Collision Layer",
    "CONT": "Container",
    "CSTY": "Combat Style",
    "DIAL": "Dialog Topic",
    "DLBR": "Dialog Branch",
    "DMGT": "Damage Type",
    "DOOR": "Door",
    "ENCH": "Object Effect",
    "ENTM": "Entitlement",
    "EQUP": "Equip Type",
    "EXPL": "Explosion",
    "FACT": "Faction",
    "FLOR": "Flora",
    "FLST": "FormID List",
    "FURN": "Furniture",
    "GLOB": "Global",
    "GMST": "Game Setting",
    "GRAS": "Grass",
    "HAZD": "Hazard",
    "HDPT": "Head Part",
    "IDLE": "Idle Animation",
    "IDLM": "Idle Marker",
    "IMAD": "Image Space Adapter",
    "IMGS": "Image Space",
    "INFO": "Dialog Response",
    "INGR": "Ingredient",
    "IPCT": "Impact",
    "IPDS": "Impact Data Set",
    "KEYM": "Key",
    "KYWD": "Keyword",
    "LAYR": "Layer",
    "LCRT": "Location Ref Type",
    "LCTN": "Location",
    "LENS": "Lens Flare",
    "LGTM": "Lighting Template",
    "LIGH": "Light",
    "LSCR": "Load Screen",
    "LTEX": "Landscape Texture",
    "LVLI": "Leveled Item",
    "LVLN": "Leveled NPC",
    "MATT": "Material Type",
    "MESG": "Message",
    "MGEF": "Magic Effect",
    "MISC": "Misc Item",
    "MOVT": "Movement Type",
    "MSTT": "Moveable Static",
    "MUSC": "Music Type",
    "MUST": "Music Track",
    "NAVM": "Navmesh",
    "NOTE": "Note",
    "NPC_": "Non-Player Character",
    "OMOD": "Object Modification",
    "OTFT": "Outfit",
    "PACK": "Package",
    "PERK": "Perk",
    "PKIN": "Pack-In",
    "PROJ": "Projectile",
    "QUST": "Quest",
    "RACE": "Race",
    "REFR": "Placed Object",
    "REGN": "Region",
    "RELA": "Relationship",
    "REVB": "Reverb Parameters",
    "RFGP": "Reference Group",
    "SCEN": "Scene",
    "SCOL": "Static Collection",
    "SMBN": "Story Manager Branch Node",
    "SMQN": "Story Manager Quest Node",
    "SNCT": "Sound Category",
    "SNDR": "Sound Descriptor",
    "SOPM": "Sound Output Model",
    "SOUN": "Sound Marker",
    "SPEL": "Spell",
    "STAT": "Static",
    "TACT": "Talking Activator",
    "TERM": "Terminal",
    "TRNS": "Transform",
    "TXST": "Texture Set",
    "VTYP": "Voice Type",
    "WATR": "Water",
    "WEAP": "Weapon",
    "WRLD": "Worldspace",
    "WTHR": "Weather",
}

# Record types that have decoded fields
DECODABLE_TYPES = frozenset({
    "WEAP", "ARMO", "ALCH", "NPC_", "QUST", "COBJ", "AMMO",
    "MISC", "BOOK", "FLOR", "GMST", "GLOB", "PERK", "ENCH",
    "MGEF", "KEYM", "CONT", "SPEL", "OMOD", "FACT", "RACE",
    "TERM", "LVLI", "LVLN", "AVIF", "ACTI", "LSCR", "MESG",
    "FURN",
})

def type_name(rec_type: str) -> str:
    """Get human-readable name for a record type."""
    return TYPE_NAMES.get(rec_type, rec_type)
